# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'mainWindow.ui'
# Created by: PyQt5 UI code generator 5.15.11
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QWidget, QVBoxLayout, QPushButton, QTableWidget


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        try:
            MainWindow.setObjectName("MainWindow")
            MainWindow.resize(1387, 932)
            self.centralwidget = QtWidgets.QWidget(MainWindow)
            self.centralwidget.setObjectName("centralwidget")

            # 创建表格部件并使用布局管理器
            layout = QVBoxLayout(self.centralwidget)
            self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
            self.tableWidget.setRowCount(50)  # 设置表格的行数
            self.tableWidget.setColumnCount(14)  # 设置表格的列数
            self.tableWidget.setObjectName("tableWidget")
            layout.addWidget(self.tableWidget)

            # 创建按钮并使用布局管理器
            button_layout = QVBoxLayout()
            for i, text in enumerate([
                "初始化产品模板", "读取选择的产品", "修改选择的产品",
                "选择待修改产品", "释放待修改产品", "遍历生成产品BOM"
            ]):
                button = self.create_button(text, i)
                button_layout.addWidget(button)
            layout.addLayout(button_layout)

            MainWindow.setCentralWidget(self.centralwidget)
            self.statusbar = QtWidgets.QStatusBar(MainWindow)
            self.statusbar.setObjectName("statusbar")
            MainWindow.setStatusBar(self.statusbar)

            self.menubar = QtWidgets.QMenuBar(MainWindow)
            self.menubar.setGeometry(QtCore.QRect(0, 0, 1387, 32))
            self.menubar.setObjectName("menubar")
            self.menucatia = QtWidgets.QMenu(self.menubar)
            self.menucatia.setObjectName("menucatia")
            self.menu = QtWidgets.QMenu(self.menubar)
            self.menu.setObjectName("menu")
            self.menu_2 = QtWidgets.QMenu(self.menubar)
            self.menu_2.setObjectName("menu_2")
            self.menu_3 = QtWidgets.QMenu(self.menubar)
            self.menu_3.setObjectName("menu_3")
            MainWindow.setMenuBar(self.menubar)
            self.menubar.addAction(self.menucatia.menuAction())
            self.menubar.addAction(self.menu.menuAction())
            self.menubar.addAction(self.menu_2.menuAction())
            self.menubar.addAction(self.menu_3.menuAction())

            self.retranslateUi(MainWindow)
            QtCore.QMetaObject.connectSlotsByName(MainWindow)
        except Exception as e:
            print(f"Error setting up UI: {e}")

    def create_button(self, text, index):
        button = QPushButton(self.centralwidget)
        button.setText(text)
        button.setObjectName(f"pushButton_{index + 1}")
        return button

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "程序窗口"))

        for i, text in enumerate([
            "初始化产品模板", "读取选择的产品", "修改选择的产品",
            "选择待修改产品", "释放待修改产品", "遍历生成产品BOM"
        ]):
            getattr(self, f"pushButton_{i + 1}").setText(_translate("MainWindow", text))

        self.menucatia.setTitle(_translate("MainWindow", "菜单"))
        self.menu.setTitle(_translate("MainWindow", "设置 "))
        self.menu_2.setTitle(_translate("MainWindow", "关于"))
        self.menu_3.setTitle(_translate("MainWindow", "作者"))